language: node_js

branches:
  only:
    - results

before_script:
  - chmod +x ./development/scripts/deploy-update-table.sh

script:
  - npm run update-table

after_success:
  ./development/scripts/deploy-update-table.sh